%% Import data from text file.
% Script for importing data from the following text file:
%
%    G:\Games\Yu-Gi-Oh! The Dawn of a New Era - YGOPRO 2\YGOPRO\deck\Dark Magician.ydk
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/03/29 19:04:59

%% Initialize variables.
filename = 'G:\Games\Yu-Gi-Oh! The Dawn of a New Era - YGOPRO 2\YGOPRO\deck\Dark Magician.ydk';
delimiter = ' ';
startRow = 3;
endRow = 42;

%% Format for each line of text:
%   column1: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r','n','UTF-8');
% Skip the BOM (Byte Order Mark).
fseek(fileID, 3, 'bof');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
DarkMagician = [dataArray{1:end-1}];


%% Create a Ranking Cell
a=10;    % #Duels
b=5;    % #Cards Startinghand
C=cell(a,b);
for k=1:a
x=randsample(DarkMagician,b);
C(k,:)=x(:);
end

%   [ii, jj] = ndgrid(1:numel(C)); %// ii, jj describe all pairs of elements from C 
%   comp = cellfun(@isequal, C(ii), C(jj)); %// test each pair for equality
%   [~, ind] = max(sum(comp,1)); %// get index of (first) most repeated element
%   result = C{ii(ind)}; %// index into C to get result

[N,Categories]=histcounts(categorical(C));
out = [num2cell(N);Categories];
out=out';
Rank=sortrows(out,'descend');

 %% Show 5 most frequent Entries

 for i=1:5
          figure;
     if exist( ['G:\Games\Yu-Gi-Oh! The Dawn of a New Era - YGOPRO 2\YGOPRO\picture\card\' char(Rank(i,2)) '.jpg']) ==2         % ==2 means file exists
         im=image(imread(( ['G:\Games\Yu-Gi-Oh! The Dawn of a New Era - YGOPRO 2\YGOPRO\picture\card\' char(Rank(i,2)) '.jpg'])));
     elseif exist( ['G:\Games\Yu-Gi-Oh! The Dawn of a New Era - YGOPRO 2\YGOPRO\picture\card\' char(Rank(i,2)) '.png']) ==2     % ==2 means file exists
         im=image(imread(( ['G:\Games\Yu-Gi-Oh! The Dawn of a New Era - YGOPRO 2\YGOPRO\picture\card\' char(Rank(i,2)) '.png'])));
     elseif exist( ['G:\Games\Yu-Gi-Oh! The Dawn of a New Era - YGOPRO 2\YGOPRO\picture\card\' char(Rank(i,2)) '.jpeg']) ==2    % ==2 means file exists
         im=image(imread(( ['G:\Games\Yu-Gi-Oh! The Dawn of a New Era - YGOPRO 2\YGOPRO\picture\card\' char(Rank(i,2)) '.jpeg'])));
     end
 end


%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans ii jj k a b comp ind x i N Categories out im;
%%im=image(imread(fullfile('G:\Games\Yu-Gi-Oh! The Dawn of a New Era - YGOPRO 2\YGOPRO\picture\card',char(myFreq(1,4))), 'jpg' ))
